name: jaguar_docstore
description: In-memory document store for Dart
version: 0.0.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_docstore

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  fixnum: '>=0.9.0 <2.0.0'
  more: '>=1.3.2 <2.0.0'
  quiver_collection: '>=1.0.0 <1.1.0'
  quiver_check: '>=1.0.0 <1.1.0'
  tuple: '>=0.4.0 <0.5.0'
  multibtree: '>=0.0.1 <0.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
